name: Deploy FWM NextJs App

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Update version of FWM App
        run: npm run release
        
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
            commit-message: Update changelog & bump version
            title: Update version
            body: Update version to reflect release changes
            branch: release-branch
            delete-branch: true
            labels: "automation"
            base: main
        
      - name: Pull request number
        run: |
            echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    
      - name: Approve pull Request
        if: ${{ steps.cpr.outputs.pull-request-number}}
        uses: hmarr/auto-approve-action@v3
        with:
            github-token: ${{ secrets.PAT }}
            pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
            review-message: "Auto approved automated PR"
      
      - name: Deploy to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd /home/fwm/scripts
            ./deploy_fwm_next_js.sh